version: "3.8"

services:
  go_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    ports:
      - "8080:8080"
    restart: always
    networks:
      - go-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - go_app
    restart: always
    networks:
      - go-network

networks:
  go-network:
    driver: bridge

